interface ZIF_CN_I_CUSTOMERCONTACT_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZCN_I_CUSTOMERCONTACT,
 ACTIVATION                     TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EDA94CAFF0DE400EFE5',
 CREATE_ZCN_I_CUSTOMERCONTACT   TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FE6FE5',
 DELETE_ZCN_I_CUSTOMERCONTACT   TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FEEFE5',
 EDIT                           TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EDA94CAFF0DE400CFE5',
 LOCK_ZCN_I_CUSTOMERCONTACT     TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FDAFE5',
 PREPARATION                    TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EDA94CAFF0DE4012FE5',
 SAVE_ZCN_I_CUSTOMERCONTACT     TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FF6FE5',
 UNLOCK_ZCN_I_CUSTOMERCONTACT   TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FDEFE5',
 UPDATE_ZCN_I_CUSTOMERCONTACT   TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FEAFE5',
 VALIDATE_ZCN_I_CUSTOMERCONTACT TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FF2FE5',
 VALIDATION                     TYPE /BOBF/ACT_KEY VALUE '000D3A02B3881EDA94CAFF0DE4010FE5',
      END OF ZCN_I_CUSTOMERCONTACT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZCN_I_CUSTOMERCONTACT,
        BEGIN OF EDIT,
 PRESERVE_CHANGES               TYPE STRING VALUE 'PRESERVE_CHANGES',
        END OF EDIT,
        BEGIN OF LOCK_ZCN_I_CUSTOMERCONTACT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZCN_I_CUSTOMERCONTACT,
        BEGIN OF PREPARATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF PREPARATION,
        BEGIN OF UNLOCK_ZCN_I_CUSTOMERCONTACT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZCN_I_CUSTOMERCONTACT,
        BEGIN OF VALIDATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF VALIDATION,
      END OF ZCN_I_CUSTOMERCONTACT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZCN_I_CUSTOMERCONTACT,
 ACTIVE_ENTITY_KEY              TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000D3A02B3881EDA94CAFF0DE4008FE5',
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '000D3A02B3881EDA94CAFF0DE400AFE5',
      END OF ZCN_I_CUSTOMERCONTACT,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZCN_I_CUSTOMERCONTACT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FD8FE5',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FD4FE5',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FE4FE5',
      END OF ZCN_I_CUSTOMERCONTACT,
      BEGIN OF ZCN_I_CUSTOMERCONTACT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FFCFE5',
      END OF ZCN_I_CUSTOMERCONTACT_LOCK,
      BEGIN OF ZCN_I_CUSTOMERCONTACT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FFAFE5',
      END OF ZCN_I_CUSTOMERCONTACT_MESSAGE,
      BEGIN OF ZCN_I_CUSTOMERCONTACT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FFEFE5',
      END OF ZCN_I_CUSTOMERCONTACT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZCN_I_CUSTOMERCONTACT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZCN_I_CUSTOMERCONTACT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FCAFE5' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZCN_I_CUSTOMERCONTACT' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZCN_I_CUSTOMERCONTACT,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EDA94CAFF0DE4014FE5',
 CENTRAL_ADMIN_DATA             TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EDA94CAFF0DE4016FE5',
 DRAFT_ACTION_CONTROL           TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EDA94CAFF0DE4022FE5',
 DRAFT_SYS_ADMIN_DATA           TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EDA94CAFF0DE4018FE5',
 DURABLE_LOCK_CLEANUP_CLEANUP   TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EDA94CAFF0DE4020FE5',
 DURABLE_LOCK_CLEANUP_DELETE    TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EDA94CAFF0DE401AFE5',
 DURABLE_LOCK_CLEANUP_FAIL_SAVE TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EDA94CAFF0DE401EFE5',
 DURABLE_LOCK_CLEANUP_SUCC_SAVE TYPE /BOBF/DET_KEY VALUE '000D3A02B3881EDA94CAFF0DE401CFE5',
      END OF ZCN_I_CUSTOMERCONTACT,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 DRAFT_CONSISTENCY              TYPE /BOBF/OBM_GROUP_KEY VALUE '000D3A02B3881EDA94CAFF0DE4002FE5',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZCN_I_CUSTOMERCONTACT          TYPE /BOBF/OBM_NODE_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FCEFE5',
 ZCN_I_CUSTOMERCONTACT_LOCK     TYPE /BOBF/OBM_NODE_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FD6FE5',
 ZCN_I_CUSTOMERCONTACT_MESSAGE  TYPE /BOBF/OBM_NODE_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FD2FE5',
 ZCN_I_CUSTOMERCONTACT_PROPERTY TYPE /BOBF/OBM_NODE_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FE2FE5',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZCN_I_CUSTOMERCONTACT,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  PARTNER                        TYPE STRING VALUE 'PARTNER',
  RLTYP                          TYPE STRING VALUE 'RLTYP',
  DFVAL                          TYPE STRING VALUE 'DFVAL',
  NAME1                          TYPE STRING VALUE 'NAME1',
  CONTACTPERSONNAME              TYPE STRING VALUE 'CONTACTPERSONNAME',
  TELNR_LONG                     TYPE STRING VALUE 'TELNR_LONG',
  SMTP_ADDR                      TYPE STRING VALUE 'SMTP_ADDR',
  LAND1                          TYPE STRING VALUE 'LAND1',
  ORT01                          TYPE STRING VALUE 'ORT01',
  PSTLZ                          TYPE STRING VALUE 'PSTLZ',
  STRAS                          TYPE STRING VALUE 'STRAS',
  HASACTIVEENTITY                TYPE STRING VALUE 'HASACTIVEENTITY',
  DRAFTENTITYCREATIONDATETIME    TYPE STRING VALUE 'DRAFTENTITYCREATIONDATETIME',
  DRAFTENTITYLASTCHANGEDATETIME  TYPE STRING VALUE 'DRAFTENTITYLASTCHANGEDATETIME',
  DRAFTENTITYCONSISTENCYSTATUS   TYPE STRING VALUE 'DRAFTENTITYCONSISTENCYSTATUS',
  ISACTIVEENTITY                 TYPE STRING VALUE 'ISACTIVEENTITY',
      END OF ZCN_I_CUSTOMERCONTACT,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZCN_I_CUSTOMERCONTACT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000D3A02B3881EDA94CAFF0DE3FD0FE5',
      END OF ZCN_I_CUSTOMERCONTACT,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_STATUS_VARIABLE,
      BEGIN OF ZCN_I_CUSTOMERCONTACT,
 DRAFT_CONSISTENCY_STATUS       TYPE /BOBF/STA_VAR_KEY VALUE '000D3A02B3881EDA94CAFF0DE4000FE5',
      END OF ZCN_I_CUSTOMERCONTACT,
    END OF SC_STATUS_VARIABLE .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZCN_I_CUSTOMERCONTACT,
 DURABLE_LOCK_CREATE_FOR_NEW    TYPE /BOBF/VAL_KEY VALUE '000D3A02B3881EDA94CAFF0DE4024FE5',
      END OF ZCN_I_CUSTOMERCONTACT,
    END OF SC_VALIDATION .
endinterface.